require: rubocop-rspec

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  ExcludedMethods:
    - context # Specs
    - describe # Specs

Metrics/AbcSize:
  Exclude:
    - lib/sources/*

Metrics/MethodLength:
  Max: 17

RSpec/MessageSpies:
  EnforcedStyle: receive

RSpec/ExampleLength:
  Max: 8
